version: '3.9'

services:
  node-beta:
    image: nodealpha
    container_name: projectnode
    ports:
      - 5000:3000
    build: .
    command: node server.js

  db:
    image: mongo
    container_name: mymongo
    ports:
      - 27017:27017