version: '3.8'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
    - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}

  app:
    build: . #construccion del dockerfile
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
